USE DATABASE MYDB;
USE SCHEMA SPS;
CREATE OR REPLACE PROCEDURE  BINDVAR()
RETURNS NUMBER(10,2)
LANGUAGE SQL
AS
$$
DECLARE 
    EMP_ID NUMBER(6) DEFAULT 7499;
    TAX_P NUMBER(10,2) DEFAULT 3.3;
    TAX_SAL NUMBER(10,2);
BEGIN
    LET G_SAL NUMBER(10,2) DEFAULT (SELECT SAL FROM MYDB.SQL_P.EMP WHERE EMPNO = :EMP_ID); --USED BIND VARIABLE HERE 
    TAX_SAL := G_SAL * TAX_P;
    RETURN TAX_SAL;
END;
$$;

CALL BINDVAR();

SELECT * FROM MYDB.SQL_P.EMP ;

CREATE OR REPLACE PROCEDURE  IDENBINDVAR()
RETURNS NUMBER(10,2)
LANGUAGE SQL
AS
$$
DECLARE 
    TAB_NAME VARCHAR DEFAULT 'MYDB.SQL_P.EMP';
    EMP_ID NUMBER(6) DEFAULT 7499;
    TAX_P NUMBER(10,2) DEFAULT 3.3;
    TAX_SAL NUMBER(10,2);
BEGIN
    LET G_SAL NUMBER(10,2) DEFAULT (SELECT SAL FROM IDENTIFIER(:TAB_NAME) WHERE EMPNO = :EMP_ID); --USED BIND VARIABLES AND IDENTIFIER HERE 
    TAX_SAL := G_SAL * TAX_P;
    RETURN TAX_SAL;
END;
$$;

CALL IDENBINDVAR();

--======================================================================
--ACCESING GLOBAL VARIABLE IN BEGIN BLOCK AND ASSIGNING VALUE
CREATE OR REPLACE PROCEDURE VAR7()
RETURNS NUMBER
LANGUAGE SQL
AS 
$$
DECLARE 
    G_SAL NUMBER(10,2);
BEGIN 

    G_SAL := 10000.00;
    RETURN G_SAL;
END;
$$;

CALL VAR7();

create or replace  table customer_table(
cust_id number(6), cust_name text, inactive_flag number(2)
) ;
insert into customer_table values
(1, 'Cust-1', 1), (2, 'Cust-2',-1), (3, 'Cust-31-1',-1),
(4, 'Cust-4',-1), (5, 'Cust-5',1);

CREATE OR REPLACE PROCEDURE VAR8()
RETURNS TEXT
LANGUAGE SQL
AS
$$
DECLARE 
    FLAG_VAL NUMBER(1) DEFAULT -1;
BEGIN 
    LET SQL_STMT := 'DELETE FROM customer_table WHERE inactive_flag =' || FLAG_VAL;

    EXECUTE IMMEDIATE  SQL_STMT;

    RETURN 'INACTIVE RECORDS ARE DELETED';
END;
$$;

CALL VAR8();

SELECT * FROM customer_table;